##library(rainbow)
#library(ggplot2); theme_set(theme_bw())
#library(ggthemes)
#library(directlabels)
#theme_update(panel.spacing=grid::unit(0,"lines"))
#library(cowplot) ## for arranging multiple plots, labeling, etc.
#library(Hmisc)

library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
aaa<-read_csv('FAOSTAT_data_1-7-2018.csv')
 aaa<-(aaa %>% select(-c(Domain,Element,Item)) 
 %>% mutate(fYear=factor(Year))
 %>% mutate(value_ktons=Value/1e6, Country=reorder(Country,-Value)
 ))
head(aaa)
gg1<-(ggplot(aaa,aes(x=Year,y=value_ktons,colour=Country,group=Country))
       +geom_line()+scale_x_continuous(breaks=seq(1995,2005,by=2)))
gg1
gg1+scale_y_log10()
library(directlabels)
direct.label(gg1+expand_limits(x=2008))+scale_color_brewer(palette = 'Dark2')
gg1+theme_bw()
gg1+theme_classic()
gg1+theme_dark()
gg1+theme_get()
gg1+theme_replace()

library(RColorBrewer)
display.brewer.all()
